//------------------------------------------------------------------------------
// <auto-generated>
//     This code was copied here by a tool: Masb.NuGet.Multiple.Targeting.Tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is copied again by the tool.
// </auto-generated>
//------------------------------------------------------------------------------
